/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0050d4",
        "primary-dim": "#0046bb",
        "primary-fixed": "#7b9cff",
        "primary-fixed-dim": "#658eff",
        "primary-container": "#7b9cff",
        "on-primary": "#f1f2ff",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#00266e",
        "on-primary-container": "#001e5a",
        "inverse-primary": "#618bff",
        "secondary": "#994100",
        "secondary-dim": "#863800",
        "secondary-fixed": "#ffc5a8",
        "secondary-fixed-dim": "#ffb28a",
        "secondary-container": "#ffc5a8",
        "on-secondary": "#fff0e9",
        "on-secondary-fixed": "#5b2400",
        "on-secondary-fixed-variant": "#883900",
        "on-secondary-container": "#793200",
        "tertiary": "#6f5900",
        "tertiary-dim": "#614d00",
        "tertiary-fixed": "#fed01b",
        "tertiary-fixed-dim": "#eec200",
        "tertiary-container": "#fed01b",
        "on-tertiary": "#fff2d3",
        "on-tertiary-fixed": "#433500",
        "on-tertiary-fixed-variant": "#645000",
        "on-tertiary-container": "#594700",
        "error": "#b31b25",
        "error-dim": "#9f0519",
        "error-container": "#fb5151",
        "on-error": "#ffefee",
        "on-error-container": "#570008",
        "background": "#f6f6ff",
        "on-background": "#272e42",
        "surface": "#f6f6ff",
        "surface-dim": "#c7d4fa",
        "surface-bright": "#f6f6ff",
        "surface-tint": "#0050d4",
        "surface-variant": "#d1dcff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef0ff",
        "surface-container": "#e2e7ff",
        "surface-container-high": "#d9e2ff",
        "surface-container-highest": "#d1dcff",
        "on-surface": "#272e42",
        "on-surface-variant": "#535b71",
        "inverse-surface": "#060e20",
        "inverse-on-surface": "#959cb5",
        "outline": "#6f768e",
        "outline-variant": "#a5adc6",
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
